# Generated by Django 5.2.8 on 2025-11-24 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TopologyLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src_port_index', models.IntegerField()),
                ('src_device', models.IntegerField()),
                ('dst_port_index', models.IntegerField()),
                ('dst_device', models.IntegerField()),
                ('is_two_way', models.BooleanField(default=False)),
                ('topology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='topology.topology')),
            ],
        ),
    ]
