# Generated by Django 5.2.8 on 2025-11-18 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TopologyLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src_port_index', models.IntegerField()),
                ('src_device', models.IntegerField()),
                ('dst_port_index', models.IntegerField()),
                ('dst_device', models.IntegerField()),
                ('is_two_way', models.BooleanField()),
            ],
        ),
    ]
