# Generated by Django 5.2.7 on 2025-10-08 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TopologyLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src_device', models.CharField(max_length=20)),
                ('src_device_port', models.IntegerField()),
                ('dst_device', models.CharField(max_length=20)),
                ('dst_device_port', models.IntegerField()),
            ],
        ),
    ]
